#preload = /home/katabame/.config/hypr/wallpaper.jpg
#wallpaper = , /home/katabame/.config/hypr/wallpaper.jpg
wallpaper {
    monitor = HDMI-A-1
    path = /home/katabame/.config/hypr/wallpaper.jpg
    fit_mode = cover
}
